In [ ]:
import numpy as np
# Creating arrays
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
zerosarr = np.zeros((3, 3),dtype=int)
print(zerosarr)
onesarr = np.ones((2, 2),dtype=int)
print(onesarr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]]


In [ ]:
zerosarr = np.zeros((3, 3),dtype=int)
print(zerosarr)
onesarr = np.ones((2, 2),dtype=int)
print(onesarr)
arangearr = np.arange(10)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]]


In [ ]:
arr = np.array([1,2,3,4,5])
reshapedarr = arr.reshape(5, 1)
print(reshapedarr)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
arr = np.array([1,2,3,4,5])
slicedarr = arr[2:4]
print(slicedarr)

[3 4]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8])
b =a.T
print(b)

[1 2 3 4 5 6 7 8]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8])
b =a.T
print(b)
b=np.split(a,4)
print(b)

[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)

[[19 22]
 [43 50]]


In [ ]:
d=np.linalg.eig(c)
print(d)

EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:
data=np.loadtxt("/content/drive/MyDrive/Dataset/TEXT.txt",dtype=int)
d=np.savetxt("/content/TEXT.txt",data)
print(d)
print(data)

None
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
arangearr = np.arange(10)
print(arangearr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arangearr = np.arange(0,1000,5)
print(arangearr)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [ ]:
arangearr = np.arange(0,1000,5)
print(arangearr)
d=np.savetxt("/content/data.txt",arangearr)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [ ]:
a=np.random.rand()
print(a)

0.41768667900578227


In [ ]:
a=np.random.randint(0,2)
print(a)

0


In [ ]:
a=np.array([[1,2],[3,4]])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
a=np.array([[1,2],[3,4]])
print(a.ndim)

2


In [ ]:
a=np.array([[1,2],[3,4]])
print(a.shape)

(2, 2)


In [ ]:
a=np.linspace(0.8,2,5)
print(a)

[0.8 1.1 1.4 1.7 2. ]


In [ ]:
a=np.arange(0,24).reshape(2,3,4)
print(a)

[[0 1 2]
 [3 4 5]]


In [ ]:
a=np.arange(0,24).reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
a=np.arange(0,24).reshape(3,2,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a*b)

[[ 5 12]
 [21 32]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a@b)

[[19 22]
 [43 50]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [ ]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a)
print(a.sum())

[[1 1 1]
 [1 1 1]]
6


In [ ]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a.sum(axis=1))

[3 3]


In [ ]:
a=np.ones((2,3),dtype=int)
print(a.sum(axis=0))

[2 2 2]


In [ ]:
a=np.floor((np.random.rand(2,12)))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
c=np.random.random((2,12))
print(c)

[[0.50921242 0.60885431 0.65888206 0.06827121 0.72195328 0.23544052
  0.20624321 0.3774405  0.43058428 0.10966035 0.98359163 0.90030314]
 [0.89832973 0.95561595 0.69114913 0.75726846 0.69623439 0.25470932
  0.31790847 0.25343906 0.24506622 0.74149203 0.47742272 0.75560054]]


In [ ]:
a=np.ceil((np.random.rand(2,12)))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
a=np.ones((2,3),dtype=int)
print(a.max(axis=1))
print(a.max())

[1 1]
1


In [ ]:
a=np.ones((2,3),dtype=int)
print(a.min())
print(a.min(axis=1))

1
[1 1]


In [ ]:
a=np.array([[1,2],[3,4]])
print(a.cumsum(axis=0))
print(a.cumsum(axis=1))

[[1 2]
 [4 6]]
[[1 3]
 [3 7]]


In [ ]:
a=np.array([2,3,5,6])
print(a.cumsum())

[ 2  5 10 16]


In [ ]:
a=np.array([2,3,5,6,4,7])
b=a.resize(3,2)
print(a)

[[2 3]
 [5 6]
 [4 7]]


In [ ]:
a=np.array([2,3,5,6,4,7])
b=a.resize(3,2)
print(a.shape)

(3, 2)


In [ ]:
a=np.array([2,3,5,6,4,7])
a.resize(2,3)
b=np.array([5,3,5,9,2,1])
b.resize(2,3)
print(np.vstack((a,b)))

[[2 3 5]
 [6 4 7]
 [5 3 5]
 [9 2 1]]


In [ ]:
a=np.array([2,3,5,6,4,7])
a.resize(2,3)
b=np.array([5,3,5,9,2,1])
b.resize(2,3)
print(np.hstack((a,b)))

[[2 3 5 5 3 5]
 [6 4 7 9 2 1]]


In [ ]:
a=np.arange(0,30).reshape(2,3,5)
print(a)
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


number of rows becomes no,of groups,
column becomes rows,
group becomes column.
and it is for dstack.

In [ ]:
import numpy as np
a=np.arange(0,6).reshape(2,3)
print(a)
print(np.dstack(a))

[[0 1 2]
 [3 4 5]]
[[[0 3]
  [1 4]
  [2 5]]]


In [ ]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a=np.full((2,2),3)
print(a)

[[3 3]
 [3 3]]


In [ ]:
x=[1,2,3]
a=np.asarray(x)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


here inner is sum of all number inside the array,and outer means one element is divding with the second array,cross means two array is mulutipcation.

In [ ]:
a=np.array([1.4,3.5,3.8])
b=np.rint(a)
print(b)

[1. 4. 4.]


In [ ]:
a=np.array([40,40,45,35])
b=np.array([10,4,5,7])
c=np.true_divide(a,b)
print(c)

[ 4. 10.  9.  5.]


In [ ]:
a=np.array([1,1,2,2,3,4])
b=np.unique(a)
print(b)

[1 2 3 4]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,8],[9,3]])
c=np.union1d(a,b)
print(c)

[1 2 3 4 8 9]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,8],[9,3]])
c=np.intersect1d(a,b)
print(c)

[1 3]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,8],[9,3]])
c=np.setdiff1d(a,b)
print(c)

[2 4]


In [ ]:
a=8
b=6
c=np.hypot(a,b)
print(c)

10.0


In [ ]:
x=np.sin(0)
print(x)

0.0


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,25,25,30])
c=np.divmod(a,b)
print(c)

(array([ 0,  1, 15,  1,  2,  2]), array([10,  0,  0, 15,  0,  0]))


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,25,25,30])
c=np.mod(a,b)
print(c)

[10  0  0 15  0  0]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,25,25,30])
c=np.divide(a,b)
print(c)

[ 0.5  1.  15.   1.6  2.   2. ]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,25,25,30])
c=np.multiply(a,b)
print(c)

[ 200  441   60 1000 1250 1800]


In [ ]:
from numpy import random
x=random.normal(size=(2,3))
print(x)

[[ 1.48768337 -0.01311147 -0.7829394 ]
 [ 0.60262038  0.2139664   1.1954997 ]]


In [ ]:
x=random.normal(loc=(1),scale=(2),size=(2,3))
print(x)

[[ 2.29963491  4.31451057  3.19351373]
 [ 0.00806637  0.67676714 -0.33091585]]


loc is means "mean" and scale means "standed devieation" and size is size

In [ ]:
x=random.binomial(n=(12),p=(0.5),size=(10))
print(x)

[5 6 2 6 6 7 4 6 6 7]


In [ ]:
x=random.poisson(lam=(2),size=(10))
print(x)

[1 1 1 1 2 1 1 2 4 2]


In [ ]:
x=random.choice([1,2,3,4])
print(x)

3


In [ ]:
x=random.choice([3,5],p=[0.2,0.8],size=(3,5))
print(x)

[[5 5 5 3 5]
 [3 3 5 5 5]
 [3 5 5 5 5]]


In [ ]:
x=random.choice([3,5],p=[0.5,0.5],size=(3,5))
print(x)

[[3 5 3 3 3]
 [5 5 3 5 3]
 [3 5 3 3 3]]
